### ISSUE TITLE
Modified Cylr Code and trying to complie it as self contained executable

### ISSUE THREAD

**Issue by tej7gandhi** [orlikoski/CyLR#104]
Hello,

I have modified Cylr code to collect particular artifacts however when I am trying to build it in Visual Studio 2019 and Publish it as self contained application .Cylr.exe requires a dll to get executed that is Cylr.dll.What is incorrect?

![image](https://user-images.githubusercontent.com/13482291/93279676-74306700-f78d-11ea-87f4-11be9e51f757.PNG)

**Comment by orlikoski** [comment]
We don't use visual studio to compile and publish so can't help you there. Try these commands as this is how we build it

32-bit Windows
dotnet publish -c release -r win-x86

64-bit Windows
dotnet publish -c release -r win-x64

**Comment by orlikoski** [comment]
After looking closer at your code it appears you were using netcoreapp2.1 which doesn't support single binary for CyLR. That's why we upgraded to netcoreapp2.2.104 that does support it

**Comment by tej7gandhi** [comment]
Thanks for your prompt response,yes that seems to be the challenge ,how can I update to netcoreapp2.2.104,I ran the commands that are provided

![image](https://user-images.githubusercontent.com/13482291/93281330-7e546480-f791-11ea-8cd2-6bfc94817cce.png)

but still it ask me for the Cylr.dll.

**Comment by orlikoski** [comment]
Install https://dotnet.microsoft.com/download/dotnet-core/2.2

**Comment by tej7gandhi** [comment]
Thanks Alan,appreciate a lot;it turns out the code that I was utilizing
older code of yours .Seems to work great now.
