### ISSUE TITLE
Using Cylr-beta with custom.txt file

### ISSUE THREAD

**Issue by tej7gandhi** [orlikoski/CyLR#105]
Hello,

I am utilizing Cylr.exe -c custom.txt to find artifacts recursively in particular directories on utilizing static, glob and regex variable it comes with Excluding invalid path error.How should I be utilizing custom.txt path?

![image](https://user-images.githubusercontent.com/13482291/94215628-dfbbb800-fea2-11ea-9ffb-1560dec28f6d.png)

**Comment by chapinb** [comment]
Hey there! Please make sure that you are using tabs instead of spaces to delimit between the pattern type and pattern content. Some editors (especially Notepad++) may use space characters when the tab key is pressed.

**Comment by tej7gandhi** [comment]
Yes,thanks ,it was related to tabs ,appreciate your prompt response.
