### ISSUE TITLE
Challenges with running Cylr from a shared network drive or directing the output to a shared network drive

### ISSUE THREAD

**Issue by tej7gandhi** [orlikoski/CyLR#106]
Hello,

I was trying to output the Cylr output to a network location "\\location\folder",can I do that utilizing Cylr and I also was trying to run Cylr from a network location "\\location\folder\Cylr.exe" ;it was not able to enumerate path?
What can I change in the code to enable this functionality?

Thanks and Regards
Tej Gandhi

**Comment by orlikoski** [comment]
unless the network folder is mapped as a drive letter that can be read by CyLR than this won't work. The solution is to map the network location as a drive letter and try again. You may have to use the non-raw mode since it won't be reading a NTFS volume at that point and may error out due to that.
