### ISSUE TITLE
Cylr.log and other file generated had to be integrated with the zip archive that is created

### ISSUE THREAD

**Issue by tej7gandhi** [orlikoski/CyLR#107]
Hello ,
How should I go about adding the new feature adding the "Cylr.log" file and a custom file that is created to the same zip archive that is generated when Cylr is executed?

Thanks and Regards
Tej Gandhi

**Comment by orlikoski** [comment]
I think the only way to accomplish this at this time is to do a second CyLR call to target those files after the first one has finished.

**Comment by chapinb** [comment]
Hey @tej7gandhi - The log file generated by CyLR at runtime is included in the resulting zip file (see https://github.com/orlikoski/CyLR/blob/f76f19f3977708ea363564ca785a6fdd6022ee08/CyLR/src/Program.cs#L276 )

**Comment by tej7gandhi** [comment]
Hi Chapin,

Thank you I will take a look ahead.

Thanks
Tej Gandhi
