### ISSUE TITLE
Publishing the App for Mac and Linux

### ISSUE THREAD

**Issue by tej7gandhi** [orlikoski/CyLR#108]
Hello,

I was able to successfully build Cylr,while publishing Cylr  am able to do it for Windowsx64 and Windowsx86;however with Mac and Linux it gives an error?
How did you publish Cylr for Linux and Mac devices?

Thanks and Regards
Tej Gandhi

**Comment by orlikoski** [comment]
The entire build process for every OS can be found by following the TravisCI build script

https://github.com/orlikoski/CyLR/blob/master/.travis.yml

**Comment by tej7gandhi** [comment]
Hello Alan,

I am not very clear on how to utilize the build script;The code gets built
cleanly while publishing it gave me error,made an edit to Publish profiles
by adding line:
<PublishReadyToRun>false </PublishReadyToRun> and it gets published now.
For MAC:
The file gets identified as a text editor file;running it from the command
line  gives me permission denied currently.How should I proceed?

Thanks and Regards
Tej Gandhi

**Comment by orlikoski** [comment]
Thanks for the feedback! 

Due to some libraries moving and being depreciated the code will need some tweaking before it can build again
