### ISSUE TITLE
Executing Cylr on Windows 2008 and Windows 8

### ISSUE THREAD

**Issue by tej7gandhi** [orlikoski/CyLR#110]
Hello All,

While executing Cylr on the following two system Windows 2008 and Windows  8 following error is observed:

"The program can't start because api-ms-win-crt-runtime-l1-1-0.dll is missing"

Is this pertaining to the Operating System or the tool?

Thanks and Regards
Tej Gandhi

**Comment by chapinb** [comment]
This is likely due to the lack of support from dotnet core, the framework CyLR was built on. More details here: https://github.com/orlikoski/CyLR/issues/109#issuecomment-755444674
