### ISSUE TITLE
FR - Ability to run CyLR Remotely

### ISSUE THREAD

**Issue by vikas891** [orlikoski/CyLR#114]
Hey Community,

To be able to run CyLR remotely via a PS command, silently (-q switch rocks). Now, how would we go about monitoring or knowing when it has finished so that we could work on uploading via API to the cloud? I know we have SFTP but would've liked plain old FTP as well ;) 

Thank you

**Comment by chapinb** [comment]
Hey @vikas891! You could monitor to see if the process is still running, or look for the presence of the output file? You could also look for the log file (if enabled) and look for a message containing "Collection complete." (just be sure to not use the same log file for a recollection, as you may pick up a prior collection's message)

Adding other cloud platforms wouldn't be much of a challenge if you wanted to take it on. The program is set up to easily allow other upload capabilities (see https://github.com/orlikoski/CyLR/blob/main/CyLR/src/Program.cs#L128 )
