### ISSUE TITLE
Possibilities to include memory acquisition features?

### ISSUE THREAD

**Issue by michael2425** [orlikoski/CyLR#118]
Hello, is it possible to include memory acquisition capabilities within this tool such as winpmem?

**Comment by chapinb** [comment]
While not "included" within CyLR, you could bundle winpmem/your CLI tool of choice in a SFX alongside CyLR, have a script run your memory collection to a static output location, then run CyLR to collect that one file with the custom patterns format.

**Comment by orlikoski** [comment]
Adding memory collection is outside of the CyLR scope but as @chapinb stated there are other tools that can be used with CyLR to accomplish this.
