### ISSUE TITLE
Version 3.0.0.0???

### ISSUE THREAD

**Issue by JTnTX** [orlikoski/CyLR#119]
Hi all,

I don't have an issue but rather a question.  I downloaded the x64 version of CyLR 2.2 but when I check the version I get the following:

C:\Users\JT\Downloads\CyLR_win-x64>cylr -h
CyLR Version 3.0.0.0

Any idea why this would be?  I have never heard mention of version 3.0.0.0 and as far as I knew, 2.2 was the latest version.

**Comment by orlikoski** [comment]
We thought this was going to be version 3.0 but turns out we went with 2.2 instead. 

The code won't build due to upstream repository changes that are now breaking the build. The easiest way out of this for now is to rename the release to 3.0 to align with the code. 

Thanks for pointing this out!

**Comment by orlikoski** [comment]
Tag 2.2.0 is now marked as release 3.0
