### ISSUE TITLE
Problem of collecting some folders due to a permissions issue

### ISSUE THREAD

**Issue by backherozzo** [orlikoski/CyLR#120]
Hi,

I know that this isn't a CyLR issue but somethings related to the Microsoft Windows permissions but after running the artifacts collection I receive a lot of errors similar to the error below (for different folder):

2021-08-16T16:35:01 [warn] Unable to enumerate all files and sub directories in C:\Windows\SysWOW64\Tasks
2021-08-16T16:35:01 [warn] Access is denied to one or more files in C:\Windows\SysWOW64\Tasks

Have you any suggestion about this issue? I started CyLR.exe from an Administrator command prompt.

**Comment by orlikoski** [comment]
I would check to see if there are any files/folders in that directory. It might throw an error if that's the case

**Comment by backherozzo** [comment]
Hi, i checked an others files and folders are present to the path the generate the error, it seems to be an ownership issue. I'm checking further if you have any suggestion could be appreciated. Thanks

**Comment by chapinb** [comment]
In some deployments I've heard of success by collecting tasks by running as system. This will vary depending on your deployment mechanism though and comes with its own drawbacks.
