### ISSUE TITLE
Drive letter choices

### ISSUE THREAD

**Issue by ashleykellyforensics** [orlikoski/CyLR#121]
Is there a way perform a collection on another drive letter that's not the C:\  .  I would love a way to choose which drive letter to collect from.

**Comment by chapinb** [comment]
Absolutely, Check out the custom path template, it has instructions for how to specify custom collections.

**Comment by ashleykellyforensics** [comment]
I went over the custom path template but I didn't see instructions for having CyLR run against a specific mount point on a windows platform.

**Comment by chapinb** [comment]
Ah, just start the file path with the mount point or drive letter you wish to use. For example “E:\totes-legit.exe” 

You can use patterns on these paths (including on the drive letter itself) as described in the documentation.
