### ISSUE TITLE
Collect UsnJrnl

### ISSUE THREAD

**Issue by jmmalcala** [orlikoski/CyLR#67]
I´m not able to collect UsnJnrl file for Windows system. This artifact is located on $Extend/$UsnJrnl -> $J.
I think CyLR can´t collect alernate data stream?¿ 
Thanks!

**Comment by InsaneTechnologies** [comment]
Add                 
@"%SystemDrive%\$Extend\$UsnJrnl:$J", 
into CollectionPaths.cs under "var defaultPaths = new List<string>"

`        public static List<string> GetPaths(Arguments arguments, List<string> additionalPaths)
        {
            var defaultPaths = new List<string>
            {
                @"%SystemDrive%\$LogFile",
                @"%SystemDrive%\$MFT",
                @"%SystemDrive%\$Recycle.Bin",
                @"%SystemDrive%\$Extend\$UsnJrnl:$J",
                @"%PROGRAMDATA%\Microsoft\Search\Data\Applications\Windows",
                @"%PROGRAMDATA%\Microsoft\Windows\Start Menu\Programs\Startup",
                @"%SYSTEMROOT%\Appcompat\Programs",
                @"%SYSTEMROOT%\inf\setupapi.dev.log",
                @"%SYSTEMROOT%\NTDS",
                @"%SYSTEMROOT%\Prefetch",
                @"%SYSTEMROOT%\SchedLgU.Txt",
                @"%SYSTEMROOT%\System32\config\SAM",
                @"%SYSTEMROOT%\System32\config\SYSTEM",
                @"%SYSTEMROOT%\System32\config\SOFTWARE",
                @"%SYSTEMROOT%\System32\config\SECURITY",
                @"%SYSTEMROOT%\System32\config\SAM.LOG1",
                @"%SYSTEMROOT%\System32\config\SYSTEM.LOG1",
                @"%SYSTEMROOT%\System32\config\SOFTWARE.LOG1",
                @"%SYSTEMROOT%\System32\config\SECURITY.LOG1",
                @"%SYSTEMROOT%\System32\config\SAM.LOG2",
                @"%SYSTEMROOT%\System32\config\SYSTEM.LOG2",
                @"%SYSTEMROOT%\System32\config\SOFTWARE.LOG2",
                @"%SYSTEMROOT%\System32\config\SECURITY.LOG2",
                @"%SYSTEMROOT%\System32\dhcp",
                @"%SYSTEMROOT%\System32\dns",
                @"%SYSTEMROOT%\System32\drivers\etc\hosts",
                @"%SYSTEMROOT%\System32\LogFiles\W3SVC1",
                @"%SYSTEMROOT%\System32\sru",
                @"%SYSTEMROOT%\System32\Tasks",
                @"%SYSTEMROOT%\System32\winevt\logs",
                @"%SYSTEMROOT%\Tasks",
            };
            defaultPaths = defaultPaths.Select(Environment.ExpandEnvironmentVariables).ToList();`

**Comment by orlikoski** [comment]
Awesome. I'll work on this in the morning

**Comment by orlikoski** [comment]
All testing passed. This will be fixed in version 2.0.1 and there will be an option to disable collection of UsnJrnl due to the amount of time it takes to collect that file. Default option will include the collection of it
