### ISSUE TITLE
CyLR does not recurse under $Recycle.Bin folder

### ISSUE THREAD

**Issue by chadtilbury** [orlikoski/CyLR#69]
When using a config file to collect files within the $Recycle.Bin folder, CyLR ignores any sub-folders and their contents.  This is a problem since the Windows Recycle Bin creates a sub-folder for each user under $Recycle.Bin and stores their files within the sub-folder.  In multiple tests I have been unable to collect files in these sub-folders.  

CyLR will collect any files directly in the $Recycle.Bin folder (these would likely be malicious as there are no legitimate reasons to see files here).  I also tested collection from user-generated folders named with a preceding "$", and CyLR was able to collect files recursively from them.  Perhaps an attribute issue?

**Comment by InsaneTechnologies** [comment]
The following changes will fix the $Recycle.bin issue. Note there's a duplicate collection for the NTUSER.DAT and UsrClass.dat files and I re-ordered a few things

            //defaultPaths = defaultPaths.Select(Environment.ExpandEnvironmentVariables).ToList();

      			//This section will attempt to collect files or folder locations under each users profile by pulling their ProfilePath from the registry and adding it in front.
      			//Add "defaultPaths.Add($@"{user.ProfilePath}" without the quotes in front of the file / path to be collected in each users profile.
            if (!Platform.IsUnixLike())
            {
              var users = FindUsers();
              foreach (var user in users)
              {
                  defaultPaths.Add($@"{user.ProfilePath}\NTUSER.DAT");
                  defaultPaths.Add($@"{user.ProfilePath}\NTUSER.DAT.LOG1");
                  defaultPaths.Add($@"{user.ProfilePath}\NTUSER.DAT.LOG2");
                  defaultPaths.Add($@"{user.ProfilePath}\AppData\Local\Microsoft\Windows\UsrClass.dat");
                  defaultPaths.Add($@"{user.ProfilePath}\AppData\Local\Microsoft\Windows\UsrClass.dat.LOG1");
                  defaultPaths.Add($@"{user.ProfilePath}\AppData\Local\Microsoft\Windows\UsrClass.dat.LOG2");
                  defaultPaths.Add($@"{user.ProfilePath}\AppData\Local\Microsoft\Windows\Explorer");
                  defaultPaths.Add($@"{user.ProfilePath}\AppData\Local\Microsoft\Windows\WebCache\");
                  defaultPaths.Add($@"{user.ProfilePath}\AppData\Local\Google\Chrome\User Data\Default\History\");
                  defaultPaths.Add($@"{user.ProfilePath}\AppData\Local\ConnectedDevicesPlatform");
                  defaultPaths.Add($@"{user.ProfilePath}\AppData\Roaming\Microsoft\Windows\PowerShell\PSReadline");
                  defaultPaths.Add($@"{user.ProfilePath}\AppData\Roaming\Microsoft\Windows\Recent");
                  defaultPaths.Add($@"{user.ProfilePath}\AppData\Roaming\Microsoft\Windows\Recent\AutomaticDestinations\");
                  defaultPaths.Add($@"{user.ProfilePath}\AppData\Roaming\Mozilla\Firefox\Profiles\");
                  defaultPaths.Add($@"%SystemDrive%\$Recycle.Bin\{user.UserKey}\");
              }
            }
            defaultPaths = defaultPaths.Select(Environment.ExpandEnvironmentVariables).ToList();

**Comment by orlikoski** [comment]
Nice! I'll work on this in the morning

**Comment by orlikoski** [comment]
Initial testing shows that this is close but not 100% working as it should. Not really sure why but this is a step in the right direction for sure!

**Comment by lkuik** [comment]
tested above changed, and re-compiled the exe, seems to collect correctly now.
Will need to recompile all installers and test each platform to ensure change didn't break anything else
Once that is done, will push to master

**Comment by davidrudduck** [comment]
Fixed. The problem with the previous suggestion I had required the path to exist in the user registry.

Instead I made it so it just steps out the $Recycle.bin path. 

`                // Enumerate Recyle Bin -- this is not ready for production yet ...
                string RecyclePath = SystemDrive + "\\$Recycle.Bin\\";
                string[] WinRecycleFolders = Directory.GetDirectories(RecyclePath);
                foreach (var RecycleBin in WinRecycleFolders)
                {
                    defaultPaths.Add($@"{RecycleBin}\");
                }`

Note "SystemDrive" is a variable that I've set elsewhere to "C:" unless called from the commandline. You could probably pull it out and instead use something like this to keep with conformity of the code, although I've not specifically tested this.

`string RecyclePath = "%SYSTEMROOT%\\$Recycle.Bin\\";
RecyclePath = RecyclePath.Select(Environment.ExpandEnvironmentVariables).ToList();`

**Comment by lkuik** [comment]
Thanks @davidrudduck will take a look at this by EOW and push a PR if the changes fixes the problem without breaking anything else
