### ISSUE TITLE
Allow sftp to specify path

### ISSUE THREAD

**Issue by InsaneTechnologies** [orlikoski/CyLR#77]
Great tool - but having issues integrating with our SFTP server (SSH on Debian)

Need to be able to tell CyLR what folder/path to upload to -- otherwise the user does not have permissions to write.....

**Comment by orlikoski** [comment]
use the `-od` and `-of` flags

https://github.com/orlikoski/CyLR/blob/master/CyLR/src/Arguments.cs#L14-L20

**Comment by InsaneTechnologies** [comment]
Ahh. That was not clear that -od could also be used to reference the sFTP....!

I'd been trying -s ftp.server.com:22/dfir and a range of things trying to get it to output to a specific location!

Thank you :)
