### ISSUE TITLE
CyLRx64 fails to run

### ISSUE THREAD

**Issue by nov3mb3r** [orlikoski/CyLR#83]
I downloaded the lastest version, run it as admin, but needs extra libraries to run properly
![default](https://user-images.githubusercontent.com/10418973/53150719-d9c06f80-35b9-11e9-81a3-441a74f437be.png)

**Comment by orlikoski** [comment]
Can you provide more details please? Were you running the 64-bit version on a 32-bit OS? What version of Windows is this running on?

**Comment by nov3mb3r** [comment]
Windows 7 Ultimate x64

**Comment by orlikoski** [comment]
I don't know what is causing it to not be able to read that `hostfxr.dll` and that is what is causing that error message.

I've confirmed the latest CyLRx64 has that package has that .zip file.  Make sure that all of the associated files (not just the CyLR.exe) are on the system and then try again.

**Comment by orlikoski** [comment]
I was able to replicate the issue and I think it has to do with the .NET CORE build itself. Will keep troubleshooting

**Comment by orlikoski** [comment]
@nov3mb3r what version of the OS are you running?
