### ISSUE TITLE
CyLR will not collect a user folder if the user doesn't exist in the registry

### ISSUE THREAD

**Issue by davidrudduck** [orlikoski/CyLR#89]
I had a case we were working where we'd used CyLR to collect our artefacts, and mid-way through the case we realised a user folder was missing.

Turns out, whilst the physical folder still existed on the system, the user had been deleted from the system - resulting in the registry not listing them, which in turn resulted in CyLR not picking up that path.

To overcome that I modified the way CyLR collects the Users folder to look for all folders within the C:\Users path instead of using the registry. This of course does have the possibility of backfiring on systems that dont use C:\Users for their storage location

>                string UserPath = SystemDrive + "\\Users\\";
>                string[] WinUserFolders = Directory.GetDirectories(UserPath);
>                foreach (var User in WinUserFolders)
>                {
>                    defaultPaths.Add($@"{User}\NTUSER.DAT");
>                    defaultPaths.Add($@"{User}\NTUSER.DAT.LOG1");
>                    defaultPaths.Add($@"{User}\NTUSER.DAT.LOG2");
>                    defaultPaths.Add($@"{User}\AppData\Local\Microsoft\Windows\UsrClass.dat");
>                    defaultPaths.Add($@"{User}\AppData\Local\Microsoft\Windows\UsrClass.dat.LOG1");
>                    defaultPaths.Add($@"{User}\AppData\Local\Microsoft\Windows\UsrClass.dat.LOG2");
>                    defaultPaths.Add($@"{User}\AppData\Local\Microsoft\Windows\Explorer");
>                    defaultPaths.Add($@"{User}\AppData\Local\Microsoft\Windows\WebCache\");
>                    defaultPaths.Add($@"{User}\AppData\Local\Google\Chrome\User Data\Default\History");
>                    defaultPaths.Add($@"{User}\AppData\Local\Google\Chrome\User Data\Default\Cookies"); // add Chrome cookies
>                    defaultPaths.Add($@"{User}\AppData\Local\Google\Chrome\User Data\Default\Bookmarks"); // add Chrome Bookmarks
>                    defaultPaths.Add($@"{User}\AppData\Local\Google\Chrome\User Data\Default\Extensions"); // add Chrome extensions
>                    defaultPaths.Add($@"{User}\AppData\Local\Google\Chrome\User Data\Default\Shortcuts"); // add Chrome shortcuts
>                    defaultPaths.Add($@"{User}\AppData\Local\Google\Chrome SxS\User Data\Default\History");
>                    defaultPaths.Add($@"{User}\AppData\Local\Google\Chrome SxS\User Data\Default\Cookies"); // Chrome Canary collection
>                    defaultPaths.Add($@"{User}\AppData\Local\Google\Chrome SxS\User Data\Default\Bookmarks");
>                    defaultPaths.Add($@"{User}\AppData\Local\Google\Chrome SxS\User Data\Default\Extensions");
>                    defaultPaths.Add($@"{User}\AppData\Local\Google\Chrome SxS\User Data\Default\Shortcuts");
>                    defaultPaths.Add($@"{User}\AppData\Local\ConnectedDevicesPlatform");
>                    defaultPaths.Add($@"{User}\AppData\Roaming\Microsoft\Windows\PowerShell\PSReadline");
>                    defaultPaths.Add($@"{User}\AppData\Roaming\Microsoft\Windows\Recent");
>                    // defaultPaths.Add($@"{user.ProfilePath}\AppData\Roaming\Microsoft\Windows\Recent\AutomaticDestinations\"); // is this redundant?
>                    defaultPaths.Add($@"{User}\AppData\Roaming\Mozilla\Firefox\Profiles");
>                }

As with my $Recycle.Bin code, SystemDrive is a variable set elsewhere to "C:". This will need to be declared or replaced with suitable environment variable paths.

**Comment by Gizmo44z** [comment]
Noticed the program will crash if the users folder doesn't exist.  Can add this to just skip if it doesn't exist.  Thanks for the updated user collection code!

            **if (!Platform.IsUnixLike())
            {
                try**

                {
                    string UserPath = Arguments.DriveLet + "\\Users\\";
                    string[] WinUserFolders = Directory.GetDirectories(UserPath);
                    **if (Directory.Exists(UserPath))**
                        foreach (var User in WinUserFolders)
                        {
                            defaultPaths.Add($@"{User}\NTUSER.DAT");
......
                        }
                }

                **catch (Exception)
                {
                    //FAIL
                }**

**Comment by lkuik** [comment]
CyLR's source code was written to use {user.ProfilePath}, and is intended to stay that way since in most cases the user will exist in registry.
Hopefully @davidrudduck  and @Gizmo44z  you were able to edit what was needed for your use cases, and thanks for the information
