### ISSUE TITLE
Is it possible to exclude files or limit the size of files being included?

### ISSUE THREAD

**Issue by 1ster** [orlikoski/CyLR#91]
To limit the size of the output archive, it would be cool to be able to exclude files that exceed a certain size, ideally by specifying a size limit, alternatively by specifying an exclude list

**Comment by joeshmoe189** [comment]
I also have the same question about this? Am I able to customize the code to pull what I would need?

**Comment by orlikoski** [comment]
CyLR doesn't have a method to do this internally

**Comment by 1ster** [comment]
Please treat as a feature request, then. Thank you.

**Comment by orlikoski** [comment]
I'd rather teach someone who wants to learn how to code and/or how to do PR's in order to get something like this done rather than do this myself.

**Comment by joeshmoe189** [comment]
@orlikoski if I change the code myself what is the best method to compile it into a new .exe?

**Comment by orlikoski** [comment]
Sure thing. The build process is contained in the Travis build files https://github.com/orlikoski/CyLR/blob/master/.travis.yml


This is the portion of the file that contains the build scripts for windows. https://github.com/orlikoski/CyLR/blob/master/.travis.yml#L29-L31

This is the portion that is called to setup the Windows environment https://github.com/orlikoski/CyLR/blob/master/.travis.yml#L21-L22

**Comment by lkuik** [comment]
hi @joeshmoe189  were you able to figure this after the guidance provided by @orlikoski ?

**Comment by joeshmoe189** [comment]
Yes I was!

**Comment by lkuik** [comment]
No further action required, closing out issue
