### ISSUE TITLE
Error occured while collecting files

### ISSUE THREAD

**Issue by jmmalcala** [orlikoski/CyLR#92]
When a try to run CyLR with PSEXEC with no arguments, CyLR shows de following error:

Error occured while collecting files:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at CyLR.read.RawFileSystem.GetSystem(String path) in C:\Users\travis\build\orlikoski\CyLR\CyLR\src\read\RawFileSystem.cs:line 65
   at CyD:\CyLR.exe exited on HSM25M2 with error code 1.

Thank you.

**Comment by orlikoski** [comment]
My guess would be that it's not being run with admin permissions

**Comment by lkuik** [comment]
@jmmalcala were you running it with administrative permissions? Typically you see this type of error when it's running without admin permissions

**Comment by lkuik** [comment]
Tested, and functionality is working. No response from @jmmalcala so closing out
