### ISSUE TITLE
Cannot open file in mode: CREATE|EXCLUSIVE|READ|WRITE error with the AWS SFTP service

### ISSUE THREAD

**Issue by matthewcummings** [orlikoski/CyLR#97]
I'm using https://aws.amazon.com/sftp/?whats-new-cards.sort-by=item.additionalFields.postDateTime&whats-new-cards.sort-order=desc but I cannot get CyLR to work with it.

It appears that I'm running into the same issue seen here https://github.com/pkg/sftp/issues/305. Do you know if there's any way I can make it work out of the box? I may open a PR if I can figure out how to add an extra flag which will accomplish this.

**Comment by orlikoski** [comment]
Since CyLR cannot use key pair authentication have you setup password auth using something what's described here? https://aws.amazon.com/blogs/storage/enable-password-authentication-for-aws-transfer-for-sftp-using-aws-secrets-manager/

**Comment by matthewcummings** [comment]
@orlikoski I did exactly that and I can connect just fine using an SFTP client.

**Comment by matthewcummings** [comment]
I've been trying some experiments with the FileMode, FileAccess and FileShare arguments here https://github.com/orlikoski/CyLR/blob/master/CyLR/src/Program.cs#L190 but nothing has worked yet.

**Comment by rTVW4nQW** [comment]
Hey, I was messing around with uploading stuff to AWS SFTP long time ago.

I'm not great with C# and I don't even remember much of what I did but I got working with sftp key and upload. Here's the diff: https://github.com/orlikoski/CyLR/compare/main...rTVW4nQW:master#diff-9b51f13c100d2429b7d58fa8d0a008c882e397e4c58fab90337b5165568ad178

Hope that helps.

**Comment by matthewcummings** [comment]
I'll try that out, thanks
