### ISSUE TITLE
Error with custom artifacts list containing {user.ProfilePath}

### ISSUE THREAD

**Issue by GenCr** [orlikoski/CyLR#98]
Good afternoon,

I'm trying to use a custom artifacts list which is a stripped down version of the default. If the list contains any folder using the {user.ProfilePath} variable I seem to get an error:

```
Error occured while collecting files:
System.ArgumentException: Path '{user.ProfilePath}\AppData\Roaming\Microsoft\Windows\Recent' did not have a drive letter!
   at CyLR.read.RawFileSystem.GetSystem(String path) in C:\Users\travis\build\orlikoski\CyLR\CyLR\src\read\RawFileSystem.cs:line 65
   at CyLR.read.RawFileSystem.GetFilesFromPath(String path)+MoveNext() in C:\Users\travis\build\orlikoski\CyLR\CyLR\src\read\RawFileSystem.cs:line 19
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CyLR.Program.CreateArchive(Arguments arguments, Stream archiveStream, IEnumerable`1 paths) in C:\Users\travis\build\orlikoski\CyLR\CyLR\src\Program.cs:line 115
   at CyLR.Program.Main(String[] args) in C:\Users\travis\build\orlikoski\CyLR\CyLR\src\Program.cs:line 87
```

I've tried various configurations. It works fine if I don't use the {user.ProfilePath} key but always fails with it.

I need to be able to iterate through all the users existing on the Windows machine.

Any way to fix this?

**Comment by lkuik** [comment]
hi @GenCr  are you able to supply the custom artifacts list you are using?
**System.ArgumentException: Path '{user.ProfilePath}\AppData\Roaming\Microsoft\Windows\Recent' did not have a drive letter!** seems to be where the error is, and perhaps one of the artifacts you are using violates this

Thanks

**Comment by GenCr** [comment]
`{user.ProfilePath}\AppData\Roaming\Microsoft\Windows\Recent` is one of the artifcats on the list that I'm using which is one of the default artifacts under the "Artifacts For All Users" section in the README.md.
If I modify the line to `%USERPROFILE%\AppData\Roaming\Microsoft\Windows\Recent` it works but then the script doesn't iterate through all the users and only runs on the user that initiated the collection.

I've also read on the README page in regards to the -c operator it says you have to specify full paths including drive letters. Could it be why it's not working?

I basically just need to provide my own list of artifact locations as well as be able to iterate through each existing user profile.

**Comment by lkuik** [comment]
If I remember correctly it's the way the call works, and that using {user.ProfilePath} cycles through all SIDs for all users as shown as specified in the following code: Whereas if you specify %userprofile% it can only run in the context of the user you run it with. 

**public static IEnumerable<UserProfile> FindUsers()
        {
            var key = Registry.LocalMachine.OpenSubKey(@"SOFTWARE\Microsoft\Windows NT\CurrentVersion\ProfileList");
            foreach (string name in key.GetSubKeyNames())
            {
                var path = $@"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\ProfileList\{name}";
                var profile = Registry.GetValue(path, "FullProfile", string.Empty);
                if (profile != null)
                {
                    var result = new UserProfile
                    {
                        UserKey = name,
                        Path = $@"{path}\ProfileImagePath",
                        ProfilePath = (string)Registry.GetValue(path, "ProfileImagePath", 0),
                        FullProfile = (int)Registry.GetValue(path, "FullProfile", 0)
                    };
                    if (result.FullProfile != -1) yield return result;
                }
            }
        }**

**Comment by GenCr** [comment]
Yes, I understand that.
The issue is why can't I specify a path that includes {user.ProfilePath} in a custom artifacts list?

**Comment by lkuik** [comment]
@GenCr  this is because the source code is configured to use {user.ProfilePath} and loops through the registry to find all users. Once it has the list of known artifacts to collect. it then runs, and collects those artifacts, and will use the {user.ProfilePath} for user related artifacts.

The custom collection is a simple list of things to collect. If you want to alter this you will need recompile the source code to include what you want or make a tool that builds the list and feeds it to CyLr
